### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by ahpxex** [Hill23333/modulelauncher-archive#1]
请问你是ModuleLauncher模块的维护者吗？我看到你star了我的modulelauncher.re ，这个名字并不是巧合，而是它本身就是c# 版本的modulelauncher模块。欢迎联络。

**Comment by Hill23333** [comment]
其实并不是。由于原版ML现在已经停更，我只是收集一下所有版本的ML模块而已。另外我在制作一个新的启动类库，所以就来参考一下。当然我现在还是个小白（

**Comment by Hill23333** [comment]
当然我也非常希望能够互相交流技术，但是我现在还是学生，很多时间回复不了消息...

**Comment by ahpxex** [comment]
可以留一个微信，当然qq也可以。

**Comment by Hill23333** [comment]
还是qq吧。因为微信这边有一些学校的事。不知道方不方便？
qq：1851466055
